/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface AllowanceSpenderInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "RECEIVER1"
      | "RECEIVER2"
      | "addExecutor"
      | "executeToReceiver1"
      | "executeToReceiver2"
      | "isExecutor"
      | "owner"
      | "removeExecutor"
      | "renounceOwnership"
      | "transferOwnership"
      | "usdt"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorAdded"
      | "ExecutorRemoved"
      | "OwnershipTransferred"
      | "TransferExecuted"
  ): EventFragment;

  encodeFunctionData(functionFragment: "RECEIVER1", values?: undefined): string;
  encodeFunctionData(functionFragment: "RECEIVER2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeToReceiver1",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeToReceiver2",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "RECEIVER1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "RECEIVER2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeToReceiver1",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeToReceiver2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isExecutor", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace ExecutorAddedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRemovedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferExecutedEvent {
  export type InputTuple = [
    executor: AddressLike,
    wallet: AddressLike,
    receiver: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    executor: string,
    wallet: string,
    receiver: string,
    amount: bigint
  ];
  export interface OutputObject {
    executor: string;
    wallet: string;
    receiver: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AllowanceSpender extends BaseContract {
  connect(runner?: ContractRunner | null): AllowanceSpender;
  waitForDeployment(): Promise<this>;

  interface: AllowanceSpenderInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  RECEIVER1: TypedContractMethod<[], [string], "view">;

  RECEIVER2: TypedContractMethod<[], [string], "view">;

  addExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  executeToReceiver1: TypedContractMethod<
    [wallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeToReceiver2: TypedContractMethod<
    [wallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  isExecutor: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  removeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "RECEIVER1"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "RECEIVER2"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeToReceiver1"
  ): TypedContractMethod<
    [wallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeToReceiver2"
  ): TypedContractMethod<
    [wallet: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isExecutor"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "ExecutorAdded"
  ): TypedContractEvent<
    ExecutorAddedEvent.InputTuple,
    ExecutorAddedEvent.OutputTuple,
    ExecutorAddedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRemoved"
  ): TypedContractEvent<
    ExecutorRemovedEvent.InputTuple,
    ExecutorRemovedEvent.OutputTuple,
    ExecutorRemovedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "TransferExecuted"
  ): TypedContractEvent<
    TransferExecutedEvent.InputTuple,
    TransferExecutedEvent.OutputTuple,
    TransferExecutedEvent.OutputObject
  >;

  filters: {
    "ExecutorAdded(address)": TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;
    ExecutorAdded: TypedContractEvent<
      ExecutorAddedEvent.InputTuple,
      ExecutorAddedEvent.OutputTuple,
      ExecutorAddedEvent.OutputObject
    >;

    "ExecutorRemoved(address)": TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;
    ExecutorRemoved: TypedContractEvent<
      ExecutorRemovedEvent.InputTuple,
      ExecutorRemovedEvent.OutputTuple,
      ExecutorRemovedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "TransferExecuted(address,address,address,uint256)": TypedContractEvent<
      TransferExecutedEvent.InputTuple,
      TransferExecutedEvent.OutputTuple,
      TransferExecutedEvent.OutputObject
    >;
    TransferExecuted: TypedContractEvent<
      TransferExecutedEvent.InputTuple,
      TransferExecutedEvent.OutputTuple,
      TransferExecutedEvent.OutputObject
    >;
  };
}
