/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { AllowanceSpender__factory } from "./AllowanceSpender__factory";
export { MockToken__factory } from "./MockToken__factory";
